# 인덱싱과 슬라이싱을 이용한 배열의 원소 조회

## 배열 인덱싱(Indexing)
- ### index
    - 배열내의 원소의 식별번호
    - 0부터 시작
- ### indexing 
    – index를 이용해 원소 조회
    - [] 표기법 사용
- ### 구문 
    - ndarray[index]
    - 양수는 지정한 index의 값을 조회한다. 
    - 음수는 뒤부터 조회한다. 
        - 마지막 index가 -1
    - 2차원배열의 경우 
        - arr[행index, 열index]
        - 파이썬 리스트와 차이점 (list[행][열])
    - N차원 배열의 경우
        - arr[0축 index, 1축 index, ..., n축 index]
- ### 팬시(fancy) 인덱싱
    - **여러개의 원소를 한번에 조회**할 경우 리스트에 담아 전달한다.
    - 다차원 배열의 경우 각 축별로 list로 지정
    - `arr[[1,2,3,4,5]]`
        - 1차원 배열(vector): 1,2,3,4,5 번 index의 원소들 한번에 조회
    - `arr[[0,3],[ 1,4]]`
        - [0,3] - 1번축 index list, [1,4] - 2번축 index list
        - 2차원 배열(matrix): [0,1], [3,4] 의 원소들 조회

In [7]:
import numpy as np

In [5]:
# shaoe : (2,3)
ls = [
    [1,2,3,],
    [10,20,30],
]
ls

[[1, 2, 3], [10, 20, 30]]

In [2]:
ls[0][1]  #그동안 우리가 숫자 2를 가져오는방법

2

In [8]:
al = np.array(ls)
al

array([[ 1,  2,  3],
       [10, 20, 30]])

In [9]:
al[0,1] #넘파이에서 숫자 2를 가져오는방법

2

In [10]:
al[0]

array([1, 2, 3])

In [12]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
print(a[1],a[6])

1 6


In [26]:
a2 = np.arange(12).reshape(2,2,3)
a2.shape

(2, 2, 3)

In [27]:
a2

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [33]:
print(a2[1])
print(a2[0,1,2]) # 5를 뽑아 내는법
print(a2[0][1][2]) #이것두가능

[[ 6  7  8]
 [ 9 10 11]]
5
5


In [36]:
# fancy indexing : 한번에 여러개 값을 조회
# 2,5,7
# a[2,5,7] # 0축:2, 1축:5, 2축: 7
a[[2,5,7]] #리스트로 조회할  index들을 묶어준다

array([2, 5, 7])

In [41]:
arr = np.array([[1,2,3],[10,20,30]])
arr

array([[ 1,  2,  3],
       [10, 20, 30]])

In [43]:
arr[0,0]

1

In [47]:
arr[1,2]

30

In [50]:
#  1하고 30가져오고싶음
arr[[0,1],[0,2]]   # 첫번째 대 가로에는 0번쨰 인덱스요소가 두번쨰 대가로에는 1번째 인덱스요소가 들어감

array([ 1, 30])

In [53]:
print(a2.shape)
a2

(2, 2, 3)


array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [58]:
#1,8,11
a2[ [0,1,1], [0,0,1], [1,2,2]]
#1 : [0,0,1]
#8 : [1,0,2]
#11: [1,1,2]

array([ 1,  8, 11])

In [60]:
# fancy index에서
#a2[0번축,1번축,2번축,..]

In [64]:
a2

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [65]:
a2[[0,1],[0,1]]  

array([[ 0,  1,  2],
       [ 9, 10, 11]])

## 슬라이싱
- 배열의 부분 집합을 하위배열로 조회 및 변경하는 방식
- ndarry[start : stop : step ]
    - start : 시작 인덱스. 기본값 0
    - stop : 끝 index. stop은 포함하지 않는다. 기본값 마지막 index
    - step : 증감 간격. 기본값 1)

In [67]:
a = np.arange(100)
print(a.shape)
a

(100,)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [69]:
a[10:50:2] #10 ~50-1까지 step : +2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [70]:
a[:50:5] # 0~50-1까지 step : +2

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [72]:
a[50: :10] #50 부터 끝까지 step :10

array([50, 60, 70, 80, 90])

In [73]:
a[1:10:] #1~9까지 step :1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
a[:] # a전부다 조회

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [76]:
a[10:1:-1] # 10 ~ 1+1, step : -1

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [77]:
# 역순으로 리버스하겠다는의미
a[::-1] # step -1 start : 마지막index,step:첫번쨰값까지 

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

### 다차원 배열 슬라이싱
- 각 축에 slicing 문법 적용
- 2차원의 경우
    - arr [행 slicing, 열 slicing]
        - `arr[:3, :]`
    - `,` 로 행과 열을 구분한 다중 슬라이싱 사용
- 다차원의 경우
    - arr[0축 slicing, 1축 slicing, ..., n축 slicing]
- slicing과 indexing 문법은 같이 쓸 수 있다.
- 모든 축에 index를 지정할 필요는 없다.

In [79]:
a = np.arange(48).reshape(6,8)
print(a.shape)
a

(6, 8)


array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [80]:
a[1:5,1:6]

array([[ 9, 10, 11, 12, 13],
       [17, 18, 19, 20, 21],
       [25, 26, 27, 28, 29],
       [33, 34, 35, 36, 37]])

In [84]:
a[1:5,1::2]

array([[ 9, 11, 13, 15],
       [17, 19, 21, 23],
       [25, 27, 29, 31],
       [33, 35, 37, 39]])

In [86]:
a[:,[0,2]] #모든 행 (0축)에서 0,2 열의값(1축)만 조회

array([[ 0,  2],
       [ 8, 10],
       [16, 18],
       [24, 26],
       [32, 34],
       [40, 42]])

### 슬라이싱은 원본에 대한 View 
- slicing한 결과는 새로운 배열을 생성하는 것이 아니라 기존 배열을 참조한다.
- slicing한 배열의 원소를 변경하면 원본 배열의 것도 바뀐다.
- 배열.copy()
    - 배열을 복사한 새로운 배열 생성
    - 복사후 처리하면 원본이 바뀌지 않는다.

In [88]:
 b = a[1:5,1::2]
b

array([[ 9, 11, 13, 15],
       [17, 19, 21, 23],
       [25, 27, 29, 31],
       [33, 35, 37, 39]])

In [102]:
b[0,0] = 9000 #원본배열건듬

In [103]:
b

array([[9000,   11,   13,   15],
       [  17,   19,   21,   23],
       [  25,   27,   29,   31],
       [  33,   35,   37,   39]])

In [93]:
a #슬라이싱한것의 값을바꿧더니 원본값도 바꼇다 주의가 필요함

array([[   0,    1,    2,    3,    4,    5,    6,    7],
       [   8, 9000,   10,   11,   12,   13,   14,   15],
       [  16,   17,   18,   19,   20,   21,   22,   23],
       [  24,   25,   26,   27,   28,   29,   30,   31],
       [  32,   33,   34,   35,   36,   37,   38,   39],
       [  40,   41,   42,   43,   44,   45,   46,   47]])

In [106]:
c = a[1:5,1::2].copy()
c[0,0] = 900
c

array([[900,  11,  13,  15],
       [ 17,  19,  21,  23],
       [ 25,  27,  29,  31],
       [ 33,  35,  37,  39]])

In [107]:
 a  # c는 카피한거라 a에 영향을 못줌

array([[   0,    1,    2,    3,    4,    5,    6,    7],
       [   8, 9000,   10,   11,   12,   13,   14,   15],
       [  16,   17,   18,   19,   20,   21,   22,   23],
       [  24,   25,   26,   27,   28,   29,   30,   31],
       [  32,   33,   34,   35,   36,   37,   38,   39],
       [  40,   41,   42,   43,   44,   45,   46,   47]])

## boolean indexing  **매우중요
- Index 연산자에 Boolean 배열을 넣으면 True인 index의 값만 조회 (False가 있는 index는 조회하지 않는다.)
- ndarray내의 원소 중에서 원하는 조건의 값들만 조회할 때 사용

In [108]:
a = np.arange(3)
a

array([0, 1, 2])

In [113]:
b = [True,False,True] # masking 
b

[True, False, True]

In [114]:
a[b] #maskung이라 부르는 이유 false는 걸러져서 못나옴

array([0, 2])

In [117]:
a + 10

array([10, 11, 12])

In [118]:
a >=1

array([False,  True,  True])

In [120]:
a[[False,True,True]]

array([1, 2])

In [122]:
a[a>=1]# 배열 a의 원소중 1이상이 값들만 조회 => 특정 조건ㅇ을 만족하는 원소들만 조회할때 boolean indexing을 사용

array([1, 2])

In [123]:
b = np.random.randint(100, size = 100)
b

array([57, 68, 81, 45, 92, 64, 79, 45, 18, 90, 95, 57,  1, 49, 43, 25, 65,
       84, 80, 82, 35, 99, 66, 74, 91, 58, 39, 63, 81, 35, 55, 18, 95, 63,
       46, 32, 52, 68, 27, 77, 64, 65, 63, 78, 26, 29, 51, 15, 71, 13, 42,
       47, 90, 49, 83, 80, 39, 63,  9, 27, 53, 77, 54, 96, 75, 25, 96,  7,
       70, 41, 98, 31, 63, 15, 34, 75, 13, 71, 30, 26, 54, 89, 21,  7, 92,
       55, 17, 72, 29, 15,  0, 10, 62, 99,  1,  5, 25, 96,  9, 92])

In [126]:
b[b >= 50]  # 50이상인 숫자만 조회

array([57, 68, 81, 92, 64, 79, 90, 95, 57, 65, 84, 80, 82, 99, 66, 74, 91,
       58, 63, 81, 55, 95, 63, 52, 68, 77, 64, 65, 63, 78, 51, 71, 90, 83,
       80, 63, 53, 77, 54, 96, 75, 96, 70, 98, 63, 75, 71, 54, 89, 92, 55,
       72, 62, 99, 96, 92])

In [127]:
b2 = b.reshape(2,50)
print(b2.shape)
b2

(2, 50)


array([[57, 68, 81, 45, 92, 64, 79, 45, 18, 90, 95, 57,  1, 49, 43, 25,
        65, 84, 80, 82, 35, 99, 66, 74, 91, 58, 39, 63, 81, 35, 55, 18,
        95, 63, 46, 32, 52, 68, 27, 77, 64, 65, 63, 78, 26, 29, 51, 15,
        71, 13],
       [42, 47, 90, 49, 83, 80, 39, 63,  9, 27, 53, 77, 54, 96, 75, 25,
        96,  7, 70, 41, 98, 31, 63, 15, 34, 75, 13, 71, 30, 26, 54, 89,
        21,  7, 92, 55, 17, 72, 29, 15,  0, 10, 62, 99,  1,  5, 25, 96,
         9, 92]])

In [128]:
b2[b2>50] # ND array에 boolean indexing을 적용하면 true값들만 1차원배열에 모아서 반환

array([57, 68, 81, 92, 64, 79, 90, 95, 57, 65, 84, 80, 82, 99, 66, 74, 91,
       58, 63, 81, 55, 95, 63, 52, 68, 77, 64, 65, 63, 78, 51, 71, 90, 83,
       80, 63, 53, 77, 54, 96, 75, 96, 70, 98, 63, 75, 71, 54, 89, 92, 55,
       72, 62, 99, 96, 92])

In [131]:
b[(b>=50) & (b<=70)]

array([57, 68, 64, 57, 65, 66, 58, 63, 55, 63, 52, 68, 64, 65, 63, 51, 63,
       53, 54, 70, 63, 54, 55, 62])

In [133]:
b[~(b>50)] #not

array([45, 45, 18,  1, 49, 43, 25, 35, 39, 35, 18, 46, 32, 27, 26, 29, 15,
       13, 42, 47, 49, 39,  9, 27, 25,  7, 41, 31, 15, 34, 13, 30, 26, 21,
        7, 17, 29, 15,  0, 10,  1,  5, 25,  9])

### np.where()
- np.where(boolean 배열) - True인 index를 반환
- boolean연산과 같이쓰면 특정 조건을 만족하는 원소의 index조회됨.
- np.where(booean 배열, True를 대체할 값, False를 대체할 값)
    - True와 False를 다른 값으로 변경한다.

In [139]:
ls = [True,False,True]
ls= np.array(ls)
np.where(ls) # 리스트에서 True값들의 index들으 반환 (반화타입 :tuple)

(array([0, 2], dtype=int64),)

In [140]:
np.where(ls,'참','거짓') #true ->'참', False -> '거짓'

array(['참', '거짓', '참'], dtype='<U2')

In [141]:
np.where(ls,'참',1) #true ->'참', False ->  원래값

array(['참', '1', '참'], dtype='<U11')

In [144]:
# b[b>=50]
np.where(b>=50)

(array([ 0,  1,  2,  4,  5,  6,  9, 10, 11, 16, 17, 18, 19, 21, 22, 23, 24,
        25, 27, 28, 30, 32, 33, 36, 37, 39, 40, 41, 42, 43, 46, 48, 52, 54,
        55, 57, 60, 61, 62, 63, 64, 66, 68, 70, 72, 75, 77, 80, 81, 84, 85,
        87, 92, 93, 97, 99], dtype=int64),)

In [145]:
np.where(b>=50,'50이상','50미만')

array(['50이상', '50이상', '50이상', '50미만', '50이상', '50이상', '50이상', '50미만',
       '50미만', '50이상', '50이상', '50이상', '50미만', '50미만', '50미만', '50미만',
       '50이상', '50이상', '50이상', '50이상', '50미만', '50이상', '50이상', '50이상',
       '50이상', '50이상', '50미만', '50이상', '50이상', '50미만', '50이상', '50미만',
       '50이상', '50이상', '50미만', '50미만', '50이상', '50이상', '50미만', '50이상',
       '50이상', '50이상', '50이상', '50이상', '50미만', '50미만', '50이상', '50미만',
       '50이상', '50미만', '50미만', '50미만', '50이상', '50미만', '50이상', '50이상',
       '50미만', '50이상', '50미만', '50미만', '50이상', '50이상', '50이상', '50이상',
       '50이상', '50미만', '50이상', '50미만', '50이상', '50미만', '50이상', '50미만',
       '50이상', '50미만', '50미만', '50이상', '50미만', '50이상', '50미만', '50미만',
       '50이상', '50이상', '50미만', '50미만', '50이상', '50이상', '50미만', '50이상',
       '50미만', '50미만', '50미만', '50미만', '50이상', '50이상', '50미만', '50미만',
       '50미만', '50이상', '50미만', '50이상'], dtype='<U4')

In [146]:
# 70이상인 값들을 모듀 70으로 반환, 70미만은 그대로 유지

In [154]:
np.where(b>=70, 70,b )

array([57, 68, 70, 45, 70, 64, 70, 45, 18, 70, 70, 57,  1, 49, 43, 25, 65,
       70, 70, 70, 35, 70, 66, 70, 70, 58, 39, 63, 70, 35, 55, 18, 70, 63,
       46, 32, 52, 68, 27, 70, 64, 65, 63, 70, 26, 29, 51, 15, 70, 13, 42,
       47, 70, 49, 70, 70, 39, 63,  9, 27, 53, 70, 54, 70, 70, 25, 70,  7,
       70, 41, 70, 31, 63, 15, 34, 70, 13, 70, 30, 26, 54, 70, 21,  7, 70,
       55, 17, 70, 29, 15,  0, 10, 62, 70,  1,  5, 25, 70,  9, 70])

In [155]:
c = np.arange(12).reshape(3,4)
print(c.shape)
c

(3, 4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [156]:
c > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [157]:
np.where(c>5)
# 반환 : tuple
# (배열,배열)
# 5보다 큰게 [1,2],[1,3][2,0],[2,1],[2,2],[2,3]에 있다는것 새로로 묶어야함

(array([1, 1, 2, 2, 2, 2], dtype=int64),
 array([2, 3, 0, 1, 2, 3], dtype=int64))

In [161]:
d = np.arange(12).reshape(2,2,3)
print(d.shape)
d

(2, 2, 3)


array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [163]:
np.where(d>7)

(array([1, 1, 1, 1], dtype=int64),
 array([0, 1, 1, 1], dtype=int64),
 array([2, 0, 1, 2], dtype=int64))

- 2차원도 마찮가지
    - 단 where는 축별로 배열이 반환된다. [0,1], [2,3] => (0,2)  (1,3)
    - 보통 Vector에 적용한다.

In [198]:
np.any(b >= 99) #배열 b에 99이상인 값이 하나라도 있는지 여부?

True

In [ ]:
np.any(b >= 90)

In [199]:
np.all(b>=90) # 배열 b의 모든 원소들이 90 이상인지 여부?

False

### 기타
- np.any(boolean 배열)
    - 배열에 True가 하나라도 있으면 True 반환
- np.all(boolean 배열)
    - 배열의 모든 원소가 True이면 True 반환

In [166]:
np.any(b >=100) # 배열 b에 100 이상인 값이 하나라도 있는지여부? False->없다

False

In [168]:
np.any(b>=90) # 배열 b에 90이상인값이 하나이상은 있구나 (True니까)

True

In [170]:
np.all(b>=90)

False

In [172]:
np.all(b>=0)

True

### 정렬
- np.sort(arr): arr을 정렬
    - 매개변수로 전달한 배열을 정렬한 새로운 배열을 반환
    - arr은 변경되지 않는다. (원본안변함)
- ndarray.sort()
    - ndarray객체 자체를 정렬(원본변환)

- np.argsort(arr): 정렬 후 index를 반환

In [174]:
x = np.array([3,4,6,9,2])
x

array([3, 4, 6, 9, 2])

In [175]:
y = np.sort(x)
y

array([2, 3, 4, 6, 9])

In [179]:
x.sort()
x

array([2, 3, 4, 6, 9])

In [180]:
z = np.array([3,4,6,9,2])
np.sort(z)[::-1] # sort자체에 내림차순 정렬이 없기때문에 이러한 방법으로 내림차순으로 정렬한다

array([9, 6, 4, 3, 2])

In [183]:
z = np.array([3,4,6,9,2])
-np.sort(-z) # 아니면 음수를 두번취해서 sort하는방법도있음(내림차순) 근데 위에방법추천

array([9, 6, 4, 3, 2])

In [184]:
a = np.array([0.1, 0.7, 0.4])
#오름차순 정렬했을때 먼저오는 index
# 0, 2, 1

In [185]:
sort_idx = np.argsort(a) # 값이아니라 인덱스를 정렬
sort_idx

array([0, 2, 1], dtype=int64)

In [186]:
a[sort_idx]

array([0.1, 0.4, 0.7])

# 다차원 배열정렬

- np.sort(배열, axis = 기준축) 기준축 생략시 마지막축을 기준으로 정렬

In [187]:
ls = [
    [1, 0, 5],
    [0, 10, 2],
    [8, 7, 6]
]
arr = np.array(ls)
arr.shape

(3, 3)

In [193]:
arr

array([[ 1,  0,  5],
       [ 0, 10,  2],
       [ 8,  7,  6]])

In [195]:
np.sort(arr, axis=0) # 0번축(세로)으로 정렬

array([[ 0,  0,  2],
       [ 1,  7,  5],
       [ 8, 10,  6]])

In [196]:
np.sort(arr, axis=1) #1번축(가로)으로 정렬

array([[ 0,  1,  5],
       [ 0,  2, 10],
       [ 6,  7,  8]])

In [197]:
np.sort(arr) # 기준축 안정하면 마지막 축을 기준으로 정렬

array([[ 0,  1,  5],
       [ 0,  2, 10],
       [ 6,  7,  8]])