# 배열을 파일에 저장 및 불러오기
- ## 바이너리 파일로 저장/불러오기
    - ### np.save("파일경로", 배열)
        - 배열을 raw 바이너리 형식으로 저장한다. (압축하지 않은)
        - 파일명에 확장자로 npy를 붙인다. (무조건 붙인다. abc.xxx 해도 abc.xxx.npy 로 저장)
    - ### np.load("파일경로") 
        - 파일에 저장된 배열을 불러온다.
    - ### np.savez("파일경로", 이름=배열, 이름=배열, ...)
        - 여러개의 배열을 저장할 때 사용
        - 파일명에 확장자로 npz가 붙는다.
        - 내부적으로 압축해서 저장한다.
        - load() 함수로 불러오면 저장된 배열목록이 반환 된다. 저장시 지정한 이름을 이용해 조회 
- ## 텍스트 파일로 저장하고 불러오기
    - ### savetxt("파일경로", 배열 [, delimiter='공백') 
        - 텍스트 형태로 저장.
        - 각 원소는 공백을 기준으로 나뉘며 delimiter 속성으로 구분자를 지정할 수 있다. (delimiter생략시 공백)
        - 1차원과 2차원 배열만 저장 가능하다. (3차원 이상은 저장이 안된다.)
    - ### loadtxt("파일경로" [,dtype=float, delimiter=공백) (dtype은 디폴트값이 float)
    - delimiter는 load,save맞춰줘야함

In [1]:
import numpy as np

In [2]:
a = np.array([1, 10, 5, 7, 20])
b = np.ones(shape= (3,3,5))
c = np.random.normal(10,2,size = (5,10)) #평균:10, 표준편차:2
print(a.shape, b.shape, c.shape)

(5,) (3, 3, 5) (5, 10)


In [9]:
# binary 파일에 배열을 저장
# 한 파일에 하나에 배열 - save(경로, 배열)
# 경로 : 상대경로(현재 working directory 기준 경로),
#        절대경로(root 디렉토리부터 전체 경로) - c:\a\b\abc
np.save("data/array_a", a) #data/array_a.npy
np.save("data/array_b.npy", b) 
np.save("data/array_c", c) #data/array.c.npy
# 저장할때 위에 .npy안붙여도 디폴트값으로 .npy가 붙어서 저장됨

In [10]:
# 불러오기(load) - load()
a2 = np.load('data/array_a.npy')
b2 = np.load('data/array_b.npy')
c2 = np.load('data/array_c.npy')

In [18]:
# 한파일에 여러개 배열 - savez(경로, 이름1=배열, 이름2=배열, ...) 이름은 변수명?이라고생각하며될듯
np.savez("data/array", a=a, b=b, c=c )

In [21]:
arrays = np.load("data/array.npz")
arrays

In [22]:
#배열들의 이름들을 조회
arrays.files

['a', 'b', 'c']

In [24]:
# 각배열을 조회 -index연산자 사용
a3 = arrays['a']
b3 = arrays['b']
c3 = arrays['c']

In [25]:
a3

array([ 1, 10,  5,  7, 20])

In [26]:
b3.shape

(3, 3, 5)

In [27]:
c3

array([[ 7.35719843,  7.21921896,  8.11203623,  9.02266698, 11.67262018,
         8.06232998,  7.28394849, 11.54147456,  8.20971704,  9.07588113],
       [12.42063155, 11.75524071, 10.66469774, 11.2494036 , 13.26088095,
        11.83425714,  4.69783774, 11.98871097, 10.65820603,  7.75166017],
       [11.06588464, 10.77261768,  8.02720461,  8.81285652,  9.64418574,
         8.93001056,  7.69049921, 12.0538393 ,  6.81916469, 10.90478361],
       [ 8.05946035,  9.43705744,  8.26361552,  9.75118442, 12.03652167,
        10.61025212,  8.84090021, 11.14696352,  9.59688923, 10.5689937 ],
       [10.44156268, 10.59985205,  8.71478003,  7.91959124, 11.26644323,
        10.41099209, 11.53420087, 11.83574133,  5.59900288, 11.06117503]])

In [ ]:
# text 파일로 저장 -> csv (comma separated value). 1차원, 2차원 배열만 저장가능
# savetext(), loadtext()

In [29]:
np.savetxt('data/a.csv', a)

In [32]:
a4 = np.loadtxt('data/a.csv', dtype=np.int)

In [40]:
a4

array([ 1, 10,  5,  7, 20])

In [41]:
print(b.shape)
np.savetxt('data/b.csv', b) # 3차원이라서 저장.txt로 저장이 안됨

(3, 3, 5)


In [39]:
print(c.shape)
np.savetxt('data/c.csv', c)

(5, 10)


In [38]:
c4 = np.loadtxt('data/c.csv')
print(c4.shape)
c4

(5, 10)


array([[ 7.35719843,  7.21921896,  8.11203623,  9.02266698, 11.67262018,
         8.06232998,  7.28394849, 11.54147456,  8.20971704,  9.07588113],
       [12.42063155, 11.75524071, 10.66469774, 11.2494036 , 13.26088095,
        11.83425714,  4.69783774, 11.98871097, 10.65820603,  7.75166017],
       [11.06588464, 10.77261768,  8.02720461,  8.81285652,  9.64418574,
         8.93001056,  7.69049921, 12.0538393 ,  6.81916469, 10.90478361],
       [ 8.05946035,  9.43705744,  8.26361552,  9.75118442, 12.03652167,
        10.61025212,  8.84090021, 11.14696352,  9.59688923, 10.5689937 ],
       [10.44156268, 10.59985205,  8.71478003,  7.91959124, 11.26644323,
        10.41099209, 11.53420087, 11.83574133,  5.59900288, 11.06117503]])

In [46]:
np.savetxt('data/c2.csv', c, delimiter=',') #구분자를 ,로 넣음

In [49]:
c5 = np.loadtxt('data/c2.csv', delimiter=',') # 구분자를 넣어줬으면 호출할때도 넣어줘야함
c5.shape

(5, 10)

In [51]:
c5

array([[ 7.35719843,  7.21921896,  8.11203623,  9.02266698, 11.67262018,
         8.06232998,  7.28394849, 11.54147456,  8.20971704,  9.07588113],
       [12.42063155, 11.75524071, 10.66469774, 11.2494036 , 13.26088095,
        11.83425714,  4.69783774, 11.98871097, 10.65820603,  7.75166017],
       [11.06588464, 10.77261768,  8.02720461,  8.81285652,  9.64418574,
         8.93001056,  7.69049921, 12.0538393 ,  6.81916469, 10.90478361],
       [ 8.05946035,  9.43705744,  8.26361552,  9.75118442, 12.03652167,
        10.61025212,  8.84090021, 11.14696352,  9.59688923, 10.5689937 ],
       [10.44156268, 10.59985205,  8.71478003,  7.91959124, 11.26644323,
        10.41099209, 11.53420087, 11.83574133,  5.59900288, 11.06117503]])

In [47]:
np.savetxt('data/c3.csv', c, delimiter='~') #구분자를 ~로 넣음, 가능하다는것만알고 ~은 쓰지말자

In [48]:
c6 = np.loadtxt('data/c3.csv', delimiter='~') # 구분자를 넣어줬으면 호출할때도 넣어줘야함
c6.shape

(5, 10)

In [53]:
c6

array([[ 7.35719843,  7.21921896,  8.11203623,  9.02266698, 11.67262018,
         8.06232998,  7.28394849, 11.54147456,  8.20971704,  9.07588113],
       [12.42063155, 11.75524071, 10.66469774, 11.2494036 , 13.26088095,
        11.83425714,  4.69783774, 11.98871097, 10.65820603,  7.75166017],
       [11.06588464, 10.77261768,  8.02720461,  8.81285652,  9.64418574,
         8.93001056,  7.69049921, 12.0538393 ,  6.81916469, 10.90478361],
       [ 8.05946035,  9.43705744,  8.26361552,  9.75118442, 12.03652167,
        10.61025212,  8.84090021, 11.14696352,  9.59688923, 10.5689937 ],
       [10.44156268, 10.59985205,  8.71478003,  7.91959124, 11.26644323,
        10.41099209, 11.53420087, 11.83574133,  5.59900288, 11.06117503]])